// packages/ai-router/services/provider-registry.ts
import { ProviderRegistryEntry, AIProviderId } from "../types";

export const PROVIDER_REGISTRY: Record<AIProviderId, ProviderRegistryEntry> = {
  openai: {
    id: "openai",
    displayName: "OpenAI",
    logo: "/logos/openai.png",
    website: "https://openai.com",
    documentation: "https://platform.openai.com/docs",
    pricingUrl: "https://openai.com/api/pricing",
    capabilities: {
      supportsStreaming: true,
      supportsVision: true,
      supportsImages: true,
      supportsAudio: true,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: true,
      supportsLongContext: true,
      supportsEmbeddings: true,
      supportsFunctionCalling: true,
      supportsFiles: true,
      supportsPDF: true,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: true,
      supportsArtifacts: true,
    },
    maxContext: 128000,
    pricing: { inputPerMillion: 2.50, outputPerMillion: 10.00 },
    apiEndpoint: "https://api.openai.com/v1",
    authType: "bearer",
  },
  claude: {
    id: "claude",
    displayName: "Anthropic Claude",
    logo: "/logos/anthropic.png",
    website: "https://anthropic.com",
    documentation: "https://docs.anthropic.com",
    pricingUrl: "https://www.anthropic.com/pricing",
    capabilities: {
      supportsStreaming: true,
      supportsVision: true,
      supportsImages: true,
      supportsAudio: false,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: true,
      supportsLongContext: true,
      supportsEmbeddings: false,
      supportsFunctionCalling: true,
      supportsFiles: true,
      supportsPDF: true,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: true,
      supportsArtifacts: true,
    },
    maxContext: 200000,
    pricing: { inputPerMillion: 3.00, outputPerMillion: 15.00 },
    apiEndpoint: "https://api.anthropic.com/v1",
    authType: "custom",
  },
  anthropic: {
    id: "anthropic",
    displayName: "Anthropic Claude",
    logo: "/logos/anthropic.png",
    website: "https://anthropic.com",
    documentation: "https://docs.anthropic.com",
    pricingUrl: "https://www.anthropic.com/pricing",
    capabilities: {
      supportsStreaming: true,
      supportsVision: true,
      supportsImages: true,
      supportsAudio: false,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: true,
      supportsLongContext: true,
      supportsEmbeddings: false,
      supportsFunctionCalling: true,
      supportsFiles: true,
      supportsPDF: true,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: true,
      supportsArtifacts: true,
    },
    maxContext: 200000,
    pricing: { inputPerMillion: 3.00, outputPerMillion: 15.00 },
    apiEndpoint: "https://api.anthropic.com/v1",
    authType: "custom",
  },
  gemini: {
    id: "gemini",
    displayName: "Google Gemini",
    logo: "/logos/gemini.png",
    website: "https://ai.google.dev",
    documentation: "https://ai.google.dev/gemini-api/docs",
    pricingUrl: "https://ai.google.dev/pricing",
    capabilities: {
      supportsStreaming: true,
      supportsVision: true,
      supportsImages: true,
      supportsAudio: true,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: false,
      supportsLongContext: true,
      supportsEmbeddings: true,
      supportsFunctionCalling: true,
      supportsFiles: true,
      supportsPDF: true,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: true,
      supportsArtifacts: true,
    },
    maxContext: 2000000,
    pricing: { inputPerMillion: 0.075, outputPerMillion: 0.30 },
    apiEndpoint: "https://generativelanguage.googleapis.com/v1beta",
    authType: "custom",
  },
  groq: {
    id: "groq",
    displayName: "Groq",
    logo: "/logos/groq.png",
    website: "https://groq.com",
    documentation: "https://console.groq.com/docs",
    pricingUrl: "https://groq.com/pricing",
    capabilities: {
      supportsStreaming: true,
      supportsVision: false,
      supportsImages: false,
      supportsAudio: true,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: false,
      supportsLongContext: false,
      supportsEmbeddings: false,
      supportsFunctionCalling: true,
      supportsFiles: false,
      supportsPDF: false,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: false,
      supportsArtifacts: false,
    },
    maxContext: 128000,
    pricing: { inputPerMillion: 0.59, outputPerMillion: 0.79 },
    apiEndpoint: "https://api.groq.com/openai/v1",
    authType: "bearer",
  },
  openrouter: {
    id: "openrouter",
    displayName: "OpenRouter",
    logo: "/logos/openrouter.png",
    website: "https://openrouter.ai",
    documentation: "https://openrouter.ai/docs",
    pricingUrl: "https://openrouter.ai/models",
    capabilities: {
      supportsStreaming: true,
      supportsVision: true,
      supportsImages: true,
      supportsAudio: true,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: true,
      supportsLongContext: true,
      supportsEmbeddings: true,
      supportsFunctionCalling: true,
      supportsFiles: true,
      supportsPDF: true,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: true,
      supportsArtifacts: true,
    },
    maxContext: 200000,
    pricing: { inputPerMillion: 1.00, outputPerMillion: 1.00 },
    apiEndpoint: "https://openrouter.ai/api/v1",
    authType: "bearer",
  },
  deepseek: {
    id: "deepseek",
    displayName: "DeepSeek",
    logo: "/logos/deepseek.png",
    website: "https://deepseek.com",
    documentation: "https://api-docs.deepseek.com",
    pricingUrl: "https://api-docs.deepseek.com/pricing",
    capabilities: {
      supportsStreaming: true,
      supportsVision: false,
      supportsImages: false,
      supportsAudio: false,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: true,
      supportsLongContext: false,
      supportsEmbeddings: false,
      supportsFunctionCalling: true,
      supportsFiles: false,
      supportsPDF: false,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: true,
      supportsArtifacts: true,
    },
    maxContext: 64000,
    pricing: { inputPerMillion: 0.14, outputPerMillion: 0.28 },
    apiEndpoint: "https://api.deepseek.com/v1",
    authType: "bearer",
  },
  together: {
    id: "together",
    displayName: "Together AI",
    logo: "/logos/together.png",
    website: "https://together.ai",
    documentation: "https://docs.together.ai",
    pricingUrl: "https://www.together.ai/pricing",
    capabilities: {
      supportsStreaming: true,
      supportsVision: false,
      supportsImages: true,
      supportsAudio: false,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: false,
      supportsLongContext: false,
      supportsEmbeddings: true,
      supportsFunctionCalling: true,
      supportsFiles: false,
      supportsPDF: false,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: false,
      supportsArtifacts: false,
    },
    maxContext: 32000,
    pricing: { inputPerMillion: 0.20, outputPerMillion: 0.20 },
    apiEndpoint: "https://api.together.xyz/v1",
    authType: "bearer",
  },
  mistral: {
    id: "mistral",
    displayName: "Mistral AI",
    logo: "/logos/mistral.png",
    website: "https://mistral.ai",
    documentation: "https://docs.mistral.ai",
    pricingUrl: "https://mistral.ai/technology/#pricing",
    capabilities: {
      supportsStreaming: true,
      supportsVision: true,
      supportsImages: false,
      supportsAudio: false,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: false,
      supportsLongContext: true,
      supportsEmbeddings: true,
      supportsFunctionCalling: true,
      supportsFiles: false,
      supportsPDF: false,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: false,
      supportsArtifacts: false,
    },
    maxContext: 128000,
    pricing: { inputPerMillion: 2.00, outputPerMillion: 6.00 },
    apiEndpoint: "https://api.mistral.ai/v1",
    authType: "bearer",
  },
  cohere: {
    id: "cohere",
    displayName: "Cohere",
    logo: "/logos/cohere.png",
    website: "https://cohere.com",
    documentation: "https://docs.cohere.com",
    pricingUrl: "https://cohere.com/pricing",
    capabilities: {
      supportsStreaming: true,
      supportsVision: false,
      supportsImages: false,
      supportsAudio: false,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: false,
      supportsLongContext: true,
      supportsEmbeddings: true,
      supportsFunctionCalling: true,
      supportsFiles: true,
      supportsPDF: true,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: false,
      supportsArtifacts: false,
    },
    maxContext: 128000,
    pricing: { inputPerMillion: 1.00, outputPerMillion: 2.00 },
    apiEndpoint: "https://api.cohere.ai/v1",
    authType: "bearer",
  },
  azure: {
    id: "azure",
    displayName: "Azure OpenAI",
    logo: "/logos/azure.png",
    website: "https://azure.microsoft.com",
    documentation: "https://learn.microsoft.com/en-us/azure/ai-services/openai",
    pricingUrl: "https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service",
    capabilities: {
      supportsStreaming: true,
      supportsVision: true,
      supportsImages: true,
      supportsAudio: true,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: true,
      supportsLongContext: true,
      supportsEmbeddings: true,
      supportsFunctionCalling: true,
      supportsFiles: true,
      supportsPDF: true,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: true,
      supportsArtifacts: true,
    },
    maxContext: 128000,
    pricing: { inputPerMillion: 2.00, outputPerMillion: 8.00 },
    apiEndpoint: "",
    authType: "bearer",
  },
  ollama: {
    id: "ollama",
    displayName: "Ollama (Local)",
    logo: "/logos/ollama.png",
    website: "https://ollama.com",
    documentation: "https://github.com/ollama/ollama/blob/main/docs/api.md",
    pricingUrl: "https://ollama.com",
    capabilities: {
      supportsStreaming: true,
      supportsVision: true,
      supportsImages: true,
      supportsAudio: false,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: false,
      supportsLongContext: true,
      supportsEmbeddings: true,
      supportsFunctionCalling: true,
      supportsFiles: true,
      supportsPDF: false,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: true,
      supportsArtifacts: true,
    },
    maxContext: 8192,
    pricing: { inputPerMillion: 0.0, outputPerMillion: 0.0 },
    apiEndpoint: "http://localhost:11434/v1",
    authType: "none",
  },
  lmstudio: {
    id: "lmstudio",
    displayName: "LM Studio",
    logo: "/logos/lmstudio.png",
    website: "https://lmstudio.ai",
    documentation: "https://lmstudio.ai/docs",
    pricingUrl: "https://lmstudio.ai",
    capabilities: {
      supportsStreaming: true,
      supportsVision: true,
      supportsImages: true,
      supportsAudio: false,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: false,
      supportsLongContext: true,
      supportsEmbeddings: true,
      supportsFunctionCalling: true,
      supportsFiles: true,
      supportsPDF: false,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: true,
      supportsArtifacts: true,
    },
    maxContext: 8192,
    pricing: { inputPerMillion: 0.0, outputPerMillion: 0.0 },
    apiEndpoint: "http://localhost:1234/v1",
    authType: "none",
  },
  xai: {
    id: "xai",
    displayName: "xAI (Grok)",
    logo: "/logos/xai.png",
    website: "https://x.ai",
    documentation: "https://docs.x.ai",
    pricingUrl: "https://docs.x.ai",
    capabilities: {
      supportsStreaming: true,
      supportsVision: false,
      supportsImages: false,
      supportsAudio: false,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: false,
      supportsLongContext: true,
      supportsEmbeddings: false,
      supportsFunctionCalling: true,
      supportsFiles: false,
      supportsPDF: false,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: false,
      supportsArtifacts: false,
    },
    maxContext: 128000,
    pricing: { inputPerMillion: 5.00, outputPerMillion: 15.00 },
    apiEndpoint: "https://api.x.ai/v1",
    authType: "bearer",
  },
  fireworks: {
    id: "fireworks",
    displayName: "Fireworks AI",
    logo: "/logos/fireworks.png",
    website: "https://fireworks.ai",
    documentation: "https://docs.fireworks.ai",
    pricingUrl: "https://fireworks.ai/pricing",
    capabilities: {
      supportsStreaming: true,
      supportsVision: true,
      supportsImages: true,
      supportsAudio: false,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: false,
      supportsLongContext: false,
      supportsEmbeddings: true,
      supportsFunctionCalling: true,
      supportsFiles: false,
      supportsPDF: false,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: false,
      supportsArtifacts: false,
    },
    maxContext: 32000,
    pricing: { inputPerMillion: 0.20, outputPerMillion: 0.80 },
    apiEndpoint: "https://api.fireworks.ai/inference/v1",
    authType: "bearer",
  },
  perplexity: {
    id: "perplexity",
    displayName: "Perplexity",
    logo: "/logos/perplexity.png",
    website: "https://perplexity.ai",
    documentation: "https://docs.perplexity.ai",
    pricingUrl: "https://docs.perplexity.ai",
    capabilities: {
      supportsStreaming: true,
      supportsVision: false,
      supportsImages: false,
      supportsAudio: false,
      supportsToolCalling: false,
      supportsJSON: false,
      supportsReasoning: true,
      supportsLongContext: false,
      supportsEmbeddings: false,
      supportsFunctionCalling: false,
      supportsFiles: false,
      supportsPDF: false,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: false,
      supportsArtifacts: false,
    },
    maxContext: 32000,
    pricing: { inputPerMillion: 5.00, outputPerMillion: 15.00 },
    apiEndpoint: "https://api.perplexity.ai",
    authType: "bearer",
  },
  ai21: {
    id: "ai21",
    displayName: "AI21 Labs",
    logo: "/logos/ai21.png",
    website: "https://ai21.com",
    documentation: "https://docs.ai21.com",
    pricingUrl: "https://www.ai21.com/pricing",
    capabilities: {
      supportsStreaming: true,
      supportsVision: false,
      supportsImages: false,
      supportsAudio: false,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: false,
      supportsLongContext: false,
      supportsEmbeddings: true,
      supportsFunctionCalling: true,
      supportsFiles: false,
      supportsPDF: false,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: false,
      supportsArtifacts: false,
    },
    maxContext: 32000,
    pricing: { inputPerMillion: 3.00, outputPerMillion: 15.00 },
    apiEndpoint: "https://api.ai21.com/studio/v1",
    authType: "bearer",
  },
  "openai-compat": {
    id: "openai-compat",
    displayName: "OpenAI Compatible Server",
    logo: "/logos/custom.png",
    website: "",
    documentation: "",
    pricingUrl: "",
    capabilities: {
      supportsStreaming: true,
      supportsVision: true,
      supportsImages: true,
      supportsAudio: true,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: true,
      supportsLongContext: true,
      supportsEmbeddings: true,
      supportsFunctionCalling: true,
      supportsFiles: true,
      supportsPDF: true,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: true,
      supportsArtifacts: true,
    },
    maxContext: 128000,
    pricing: { inputPerMillion: 0.00, outputPerMillion: 0.00 },
    apiEndpoint: "",
    authType: "bearer",
  },
  custom: {
    id: "custom",
    displayName: "Custom Endpoint",
    logo: "/logos/custom.png",
    website: "",
    documentation: "",
    pricingUrl: "",
    capabilities: {
      supportsStreaming: true,
      supportsVision: true,
      supportsImages: true,
      supportsAudio: true,
      supportsToolCalling: true,
      supportsJSON: true,
      supportsReasoning: true,
      supportsLongContext: true,
      supportsEmbeddings: true,
      supportsFunctionCalling: true,
      supportsFiles: true,
      supportsPDF: true,
      supportsCode: true,
      supportsMarkdown: true,
      supportsMermaid: true,
      supportsArtifacts: true,
    },
    maxContext: 128000,
    pricing: { inputPerMillion: 0.00, outputPerMillion: 0.00 },
    apiEndpoint: "",
    authType: "bearer",
  },
};
