import { NextRequest, NextResponse } from "next/server";
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from "docx";
import JSZip from "jszip";
import ExcelJS from "exceljs";
import { escapeHTML } from "packages/security";

export async function POST(req: NextRequest) {
  try {
    const { filename = "Document", type = "pdf", content = "", title = "Career Copilot Generated Document" } = await req.json();
    const safeFilename = filename.replace(/[^a-zA-Z0-9_\-.]/g, "_");

    // 1. DOCX (Word Document)
    if (type === "docx" || safeFilename.endsWith(".docx")) {
      const paragraphs: Paragraph[] = [
        new Paragraph({
          text: title,
          heading: HeadingLevel.HEADING_1,
          spacing: { after: 200 },
        }),
      ];

      const lines = content.split("\n");
      for (const line of lines) {
        if (line.startsWith("# ")) {
          paragraphs.push(new Paragraph({ text: line.replace("# ", ""), heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 100 } }));
        } else if (line.startsWith("## ")) {
          paragraphs.push(new Paragraph({ text: line.replace("## ", ""), heading: HeadingLevel.HEADING_2, spacing: { before: 150, after: 80 } }));
        } else if (line.startsWith("### ")) {
          paragraphs.push(new Paragraph({ text: line.replace("### ", ""), heading: HeadingLevel.HEADING_3, spacing: { before: 100, after: 60 } }));
        } else if (line.startsWith("- ") || line.startsWith("* ")) {
          paragraphs.push(new Paragraph({ text: line.replace(/^[-*]\s+/, ""), bullet: { level: 0 } }));
        } else if (line.trim().length > 0) {
          paragraphs.push(new Paragraph({ children: [new TextRun(line)] }));
        }
      }

      const doc = new Document({
        sections: [{ properties: {}, children: paragraphs }],
      });

      const buffer = await Packer.toBuffer(doc);
      return new NextResponse(new Uint8Array(buffer), {
        headers: {
          "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          "Content-Disposition": `attachment; filename="${safeFilename.endsWith(".docx") ? safeFilename : safeFilename + ".docx"}"`,
        },
      });
    }

    // 2. EXCEL / CSV Spreadsheet
    if (type === "excel" || type === "csv" || safeFilename.endsWith(".xlsx") || safeFilename.endsWith(".csv")) {
      const workbook = new ExcelJS.Workbook();
      const worksheet = workbook.addWorksheet("Career Data");
      
      const lines = content.split("\n").filter((l: string) => l.trim().length > 0);
      lines.forEach((line: string) => {
        const cells = line.includes(",") ? line.split(",") : line.split("\t");
        worksheet.addRow(cells.map((c: string) => c.replace(/^[-*|]\s*/, "").trim()));
      });

      if (type === "csv" || safeFilename.endsWith(".csv")) {
        const csvContent = lines.map((l: string) => l.replace(/^[-*|]\s*/, "").trim()).join("\n");
        return new NextResponse(csvContent, {
          headers: {
            "Content-Type": "text/csv; charset=utf-8",
            "Content-Disposition": `attachment; filename="${safeFilename.endsWith(".csv") ? safeFilename : safeFilename + ".csv"}"`,
          },
        });
      }

      const buffer = await workbook.xlsx.writeBuffer();
      return new NextResponse(new Uint8Array(buffer as ArrayBuffer), {
        headers: {
          "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
          "Content-Disposition": `attachment; filename="${safeFilename.endsWith(".xlsx") ? safeFilename : safeFilename + ".xlsx"}"`,
        },
      });
    }

    // 3. ZIP Archive
    if (type === "zip" || safeFilename.endsWith(".zip")) {
      const zip = new JSZip();
      zip.file("README.md", `# ${title}\n\nGenerated by Career Copilot AI Brain.\n\n${content}`);
      zip.file("Document.txt", content);

      const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });
      return new NextResponse(new Uint8Array(zipBuffer), {
        headers: {
          "Content-Type": "application/zip",
          "Content-Disposition": `attachment; filename="${safeFilename.endsWith(".zip") ? safeFilename : safeFilename + ".zip"}"`,
        },
      });
    }

    // 4. JSON
    if (type === "json" || safeFilename.endsWith(".json")) {
      let jsonPayload = { title, date: new Date().toISOString(), content };
      try {
        jsonPayload = JSON.parse(content);
      } catch {}

      return new NextResponse(JSON.stringify(jsonPayload, null, 2), {
        headers: {
          "Content-Type": "application/json",
          "Content-Disposition": `attachment; filename="${safeFilename.endsWith(".json") ? safeFilename : safeFilename + ".json"}"`,
        },
      });
    }

    // 5. MARKDOWN / TXT
    if (type === "md" || type === "txt" || safeFilename.endsWith(".md") || safeFilename.endsWith(".txt")) {
      return new NextResponse(content, {
        headers: {
          "Content-Type": type === "md" ? "text/markdown; charset=utf-8" : "text/plain; charset=utf-8",
          "Content-Disposition": `attachment; filename="${safeFilename}"`,
        },
      });
    }

    // 6. DEFAULT: Printable HTML-to-PDF / PDF Document
    const htmlPdf = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${escapeHTML(title)}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 40px; background: #ffffff; color: #0f172a; line-height: 1.6; }
    h1 { color: #0284c7; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; font-size: 24px; }
    h2 { color: #4338ca; margin-top: 24px; font-size: 18px; border-bottom: 1px solid #f1f5f9; padding-bottom: 4px; }
    h3 { color: #1e293b; font-size: 15px; }
    pre { background: #f8fafc; padding: 12px; border-radius: 8px; font-size: 13px; overflow-x: auto; border: 1px solid #e2e8f0; }
    ul { padding-left: 20px; }
    li { margin-bottom: 6px; }
    .badge { display: inline-block; padding: 4px 8px; font-size: 11px; background: #e0f2fe; color: #0369a1; border-radius: 4px; font-weight: bold; margin-bottom: 16px; }
    footer { margin-top: 40px; pt-10; border-top: 1px solid #e2e8f0; font-size: 11px; color: #64748b; text-align: center; }
  </style>
</head>
<body>
  <div class="badge">Generated by Career Copilot AI</div>
  <h1>${escapeHTML(title)}</h1>
  <div>${escapeHTML(content).replace(/\n/g, "<br/>")}</div>
  <footer>Career Agents AI Platform · Generated on ${new Date().toLocaleDateString()}</footer>
  <script>window.onload = function() { window.print(); };</script>
</body>
</html>`;

    return new NextResponse(htmlPdf, {
      headers: {
        "Content-Type": type === "pdf" ? "text/html; charset=utf-8" : "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="${safeFilename.endsWith(".pdf") ? safeFilename.replace(/\.pdf$/, ".html") : safeFilename}"`,
      },
    });
  } catch (e: any) {
    return NextResponse.json({ success: false, error: e.message }, { status: 500 });
  }
}
