import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '../..');

export function compileHtmlReport(title, score, data, type = 'general') {
  const categoriesHtml = Object.entries(data.categoryScores || {}).map(([cat, val]) => `
    <div class="card">
      <div class="card-title">${cat.charAt(0).toUpperCase() + cat.slice(1)}</div>
      <div class="score-bar-container">
        <div class="score-bar" style="width: ${val}%"></div>
      </div>
      <div style="text-align: right; margin-top: 5px; font-weight: bold;">${val}%</div>
    </div>
  `).join('');

  const recommendationsHtml = (data.recommendations || data.suggestions || []).map(rec => `
    <li class="recommendation-item">${rec}</li>
  `).join('');

  let detailsHtml = '';
  if (type === 'github') {
    detailsHtml = `
      <h2>Technical Repository Profile Metrics</h2>
      <p>Public Repositories: <strong>${data.publicReposCount || 0}</strong></p>
      <p>Total Community Stars: <strong>${data.starsCount || 0}</strong></p>
      <p>Forks Count: <strong>${data.forksCount || 0}</strong></p>
      <p>Languages: <strong>${(data.languages || []).join(', ')}</strong></p>
    `;
  }

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      background-color: #0b0f19;
      color: #e2e8f0;
      margin: 0;
      padding: 40px;
    }
    .container {
      max-width: 900px;
      margin: 0 auto;
      background: rgba(17, 24, 39, 0.7);
      backdrop-filter: blur(12px);
      border: 1px solid rgba(255, 255, 255, 0.1);
      border-radius: 16px;
      padding: 40px;
      box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
    }
    h1 {
      color: #38bdf8;
      font-size: 32px;
      margin-bottom: 5px;
    }
    .score-badge {
      display: inline-block;
      padding: 10px 20px;
      background: linear-gradient(135deg, #0284c7, #0369a1);
      border-radius: 9999px;
      font-weight: bold;
      font-size: 20px;
      margin-top: 10px;
    }
    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 20px;
      margin-top: 30px;
    }
    .card {
      background: rgba(255, 255, 255, 0.03);
      border: 1px solid rgba(255, 255, 255, 0.05);
      border-radius: 12px;
      padding: 20px;
    }
    .card-title {
      font-weight: bold;
      text-transform: uppercase;
      font-size: 14px;
      color: #94a3b8;
      margin-bottom: 10px;
    }
    .score-bar-container {
      height: 8px;
      background: rgba(255, 255, 255, 0.1);
      border-radius: 4px;
      overflow: hidden;
    }
    .score-bar {
      height: 100%;
      background: linear-gradient(90deg, #38bdf8, #0ea5e9);
      border-radius: 4px;
    }
    .recommendations {
      margin-top: 40px;
    }
    .recommendation-item {
      padding: 12px;
      background: rgba(239, 68, 68, 0.05);
      border-left: 4px solid #ef4444;
      margin-bottom: 10px;
      border-radius: 0 8px 8px 0;
      list-style-type: none;
    }
    footer {
      text-align: center;
      margin-top: 50px;
      font-size: 12px;
      color: #64748b;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>${title}</h1>
    <div class="score-badge">Overall Score: ${score}%</div>
    
    <div class="grid">
      ${categoriesHtml}
    </div>

    <div class="recommendations">
      <h2>Actionable Growth Checklist</h2>
      <ul>
        ${recommendationsHtml}
      </ul>
    </div>

    <div style="margin-top: 40px;">
      ${detailsHtml}
    </div>

    <footer>
      Generated by Career OS (Open-Source Career Operating System v2.0.0)
    </footer>
  </div>
</body>
</html>
  `;
}

export function writeShareableReport(name, score, reportData, type) {
  const outDir = path.join(root, 'exports', 'shareable-reports');
  fs.mkdirSync(outDir, { recursive: true });

  const baseName = `${type}-${name.toLowerCase().replace(/[^a-z0-9]/g, '-')}`;

  fs.writeFileSync(
    path.join(outDir, `${baseName}.json`),
    JSON.stringify({ reportType: type, score, data: reportData }, null, 2),
    'utf8'
  );

  const htmlContent = compileHtmlReport(`${type.toUpperCase()} Performance Report for ${name}`, score, reportData, type);
  fs.writeFileSync(path.join(outDir, `${baseName}.html`), htmlContent, 'utf8');

  return {
    jsonPath: path.join(outDir, `${baseName}.json`),
    htmlPath: path.join(outDir, `${baseName}.html`)
  };
}
