// api/reports/generate/route.ts — Compile HTML/Markdown/JSON career reports

import { NextResponse } from "next/server";

function gradeFromScore(score: number): string {
  if (score >= 90) return "A+";
  if (score >= 80) return "A";
  if (score >= 70) return "B+";
  if (score >= 60) return "B";
  if (score >= 50) return "C";
  return "D";
}

function generateMarkdownReport(data: any): string {
  const { metrics, profile, resumeAnalysis, githubAnalysis, linkedinAnalysis, generatedAt } = data;

  return `# Career OS — Career Analysis Report

**Generated:** ${new Date(generatedAt).toLocaleString()}
**Profile:** ${profile?.name || "Anonymous"} | ${profile?.targetRole || "Software Engineer"}

---

## Career Score Overview

| Module | Score | Grade |
|--------|-------|-------|
| **Overall Career Score** | ${metrics?.careerScore || 0}/100 | ${gradeFromScore(metrics?.careerScore || 0)} |
| Resume Studio | ${metrics?.resumeScore || 0}/100 | ${gradeFromScore(metrics?.resumeScore || 0)} |
| GitHub Analyzer | ${metrics?.githubScore || 0}/100 | ${gradeFromScore(metrics?.githubScore || 0)} |
| LinkedIn Optimizer | ${metrics?.linkedinScore || 0}/100 | ${gradeFromScore(metrics?.linkedinScore || 0)} |
| Interview Lab | ${metrics?.interviewScore || 0}/100 | ${gradeFromScore(metrics?.interviewScore || 0)} |
| Job Tracker | ${metrics?.applicationScore || 0}/100 | ${gradeFromScore(metrics?.applicationScore || 0)} |

---

## Resume Analysis
${
  resumeAnalysis
    ? `
**File:** ${resumeAnalysis.fileName}
**ATS Score:** ${resumeAnalysis.atsScore}/100
**Analyzed:** ${new Date(resumeAnalysis.analyzedAt).toLocaleDateString()}

### Section Coverage
${Object.entries(resumeAnalysis.sections || {})
  .map(([k, v]) => `- ${k}: ${v ? "✅" : "❌"}`)
  .join("\n")}

### Missing Keywords
${resumeAnalysis.missingKeywords?.join(", ") || "None"}

### Recommendations
${resumeAnalysis.recommendations?.map((r: string) => `- ${r}`).join("\n") || "No recommendations"}
`
    : "No resume analysis available. Upload your resume in Resume Studio."
}

---

## GitHub Portfolio
${
  githubAnalysis
    ? `
**Username:** @${githubAnalysis.username}
**Portfolio Score:** ${githubAnalysis.portfolioScore}/100
**Public Repos:** ${githubAnalysis.publicRepos} | **Total Stars:** ${githubAnalysis.totalStars}
**README Quality:** ${githubAnalysis.readmeGrade}

### Top Languages
${githubAnalysis.languages?.map((l: any) => `- ${l.name}: ${l.percent}%`).join("\n") || "N/A"}

### Recommendations
${githubAnalysis.recommendations?.map((r: string) => `- ${r}`).join("\n") || "No recommendations"}
`
    : "No GitHub analysis available. Run the GitHub Analyzer."
}

---

## LinkedIn Profile
${
  linkedinAnalysis
    ? `
**Visibility Score:** ${linkedinAnalysis.overallScore}/100
**Headline Score:** ${linkedinAnalysis.headlineScore}/100
**Summary Score:** ${linkedinAnalysis.summaryScore}/100
**Keyword Density:** ${linkedinAnalysis.keywordDensity}%

### Recommendations
${linkedinAnalysis.recommendations?.map((r: string) => `- ${r}`).join("\n") || "No recommendations"}
`
    : "No LinkedIn analysis available. Run the LinkedIn Optimizer."
}

---

## Action Plan

### Immediate (This Week)
${metrics?.resumeScore < 60 ? "1. Re-upload your resume and act on ATS recommendations\n" : ""}${metrics?.githubScore < 60 ? "2. Add READMEs to your top 3 GitHub repositories\n" : ""}${metrics?.linkedinScore < 60 ? "3. Rewrite your LinkedIn headline using the AI suggestions\n" : ""}${metrics?.interviewScore < 60 ? "4. Complete at least one mock interview session in Interview Lab\n" : ""}

### Next 30 Days
- Target ${profile?.targetCompany || "your dream company"} specifically with PrepHub
- Track 5+ applications in the Job Tracker
- Aim for a Career Score of ${Math.min(100, (metrics?.careerScore || 0) + 15)}+

---

*Generated by Career OS v2.0 — AI-Powered Career Intelligence Platform*
`;
}

function generateHTMLReport(markdown: string, data: any): string {
  const { metrics, profile } = data;
  const score = metrics?.careerScore || 0;
  const scoreColor = score >= 80 ? "#34d399" : score >= 60 ? "#38bdf8" : score >= 40 ? "#fbbf24" : "#f87171";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Career OS Report — ${profile?.name || "Career Analysis"}</title>
<style>
  body { font-family: 'Inter', system-ui, sans-serif; background: #0a0f1e; color: #e2e8f0; max-width: 860px; margin: 0 auto; padding: 2rem; line-height: 1.6; }
  h1 { background: linear-gradient(135deg, #38bdf8, #818cf8); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-size: 2rem; margin-bottom: 0.25rem; }
  h2 { color: #94a3b8; font-size: 1.1rem; font-weight: 600; border-bottom: 1px solid #1e293b; padding-bottom: 0.5rem; margin-top: 2rem; }
  table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
  th, td { padding: 0.75rem 1rem; text-align: left; border: 1px solid #1e293b; }
  th { background: #0f172a; color: #94a3b8; font-size: 0.85rem; }
  td { background: #0d1526; }
  .score-badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 9999px; font-weight: 700; font-size: 2rem; color: ${scoreColor}; border: 2px solid ${scoreColor}30; }
  .meta { color: #64748b; font-size: 0.85rem; margin-bottom: 2rem; }
  code { background: #0f172a; padding: 0.15rem 0.5rem; border-radius: 4px; font-size: 0.85rem; color: #34d399; }
  footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #1e293b; color: #475569; font-size: 0.8rem; text-align: center; }
</style>
</head>
<body>
<h1>Career OS</h1>
<div class="meta">Career Analysis Report · Generated ${new Date().toLocaleString()} · ${profile?.name || "Profile"}</div>
<div style="margin: 2rem 0;">
  <div class="score-badge">${score}</div>
  <span style="color: #64748b; margin-left: 0.75rem;">/ 100 Career Score</span>
</div>
<pre style="white-space: pre-wrap; color: #cbd5e1; background: #0d1526; padding: 1.5rem; border-radius: 0.75rem; border: 1px solid #1e293b; font-size: 0.85rem; line-height: 1.7;">${markdown.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</pre>
<footer>Generated by Career OS v2.0 — AI-Powered Career Intelligence Platform</footer>
</body>
</html>`;
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { format = "markdown", ...reportData } = body;

    const generatedAt = new Date().toISOString();
    const data = { ...reportData, generatedAt };

    if (format === "json") {
      return NextResponse.json({ report: data, format: "json", generatedAt });
    }

    const markdown = generateMarkdownReport(data);

    if (format === "html") {
      const html = generateHTMLReport(markdown, data);
      return new NextResponse(html, {
        headers: { "Content-Type": "text/html", "Content-Disposition": "attachment; filename=career-report.html" },
      });
    }

    // Default: markdown
    return new NextResponse(markdown, {
      headers: {
        "Content-Type": "text/markdown",
        "Content-Disposition": "attachment; filename=career-report.md",
      },
    });
  } catch (e: any) {
    return NextResponse.json({ error: e.message || "Report generation failed" }, { status: 500 });
  }
}
