// apps/web/src/app/api/reports/generate/route.ts
import { NextRequest, NextResponse } from "next/server";
import { enforceRequestLimits } from "packages/security";

export async function POST(req: NextRequest) {
  try {
    const clientIp = (req.headers.get("x-forwarded-for")?.split(",")[0] || req.headers.get("x-real-ip") || "127.0.0.1").trim();
    const limitResponse = enforceRequestLimits(req, clientIp);
    if (limitResponse) return limitResponse;

    const { profile, metrics, format, type, data } = await req.json();

    const timestamp = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });

    const reportTitle = `${type === "full" ? "Comprehensive Career" : type.toUpperCase()} Report`;

    if (format === "json") {
      return NextResponse.json({
        title: reportTitle,
        generatedAt: timestamp,
        profile,
        metrics,
        details: data || {},
      });
    }

    let markdown = `# ${reportTitle}
Generated by Career Agents on ${timestamp}

## Candidate Profile
- **Name**: ${profile?.name || "Guest User"}
- **Target Role**: ${profile?.targetRole || "Software Engineer"}
- **Email**: ${profile?.email || "N/A"}

## Core Performance Metrics
- **Overall Career Score**: ${metrics?.careerScore || 0}/100
- **Resume Score**: ${metrics?.resumeScore || 0}/100
- **GitHub Portfolio Score**: ${metrics?.githubScore || 0}/100
- **LinkedIn Visibility Score**: ${metrics?.linkedinScore || 0}/100
- **Mock Interview Score**: ${metrics?.interviewScore || 0}/100

---

## Detailed Assessment & Action Plan
`;

    if (type === "resume" && data?.weakBullets) {
      markdown += `\n### Resume Studio Review
- **ATS Score**: ${data.atsScore || 0}%
- **Identified Keyword Gaps**: ${data.missingKeywords?.join(", ") || "None"}
- **Weak Bullets Audited**:
${data.weakBullets.map((b: any) => `  - *Original*: "${b.original}"\n    *Issue*: ${b.issue}\n    *Recommended*: "${b.suggested}"`).join("\n")}
`;
    } else if (type === "github" && data?.recommendations) {
      markdown += `\n### GitHub Audit Report
- **Portfolio Grade**: ${data.readmeGrade || "Good"}
- **Public Repositories Audited**: ${data.publicRepos || 0}
- **Action Items**:
${data.recommendations.map((r: string) => `  - [ ] ${r}`).join("\n")}
`;
    } else if (type === "linkedin" && data?.headlineAnalysis) {
      markdown += `\n### LinkedIn Optimization Report
- **Recruiter Scan Score**: ${data.recruiterScore || 0}/100
- **Headline Suggestions**:
${data.headlineAnalysis.rewrites?.map((rw: string) => `  - *Suggested Headline*: "${rw}"`).join("\n") || "No suggestions available."}
- **Summary Suggestions**:
${data.summaryAnalysis?.suggestions?.map((s: string) => `  - ${s}`).join("\n") || "None"}
`;
    } else if (type === "interview" && data?.scorecard) {
      const card = data.scorecard;
      markdown += `\n### Interview Lab Performance Log
- **Round**: ${data.round || "Technical"} at ${data.company || "Target Company"}
- **STAR Structure Score**: ${card.dimensions?.starStructure || 0}/100
- **Communication Score**: ${card.dimensions?.communication || 0}/100
- **Technical Accuracy Score**: ${card.dimensions?.technicalAccuracy || 0}/100
- **Strengths**:
${card.strengths?.map((s: string) => `  - ${s}`).join("\n") || "None listed"}
- **Areas of Improvement**:
${card.improvements?.map((i: string) => `  - ${i}`).join("\n") || "None listed"}
`;
    } else {
      // Full report
      markdown += `
### 1. Resume Optimization Status
Score: ${metrics?.resumeScore || 0}%
Focus on eliminating passive phrasing and embedding target keywords in high-impact XYZ templates.

### 2. GitHub Portfolio Status
Score: ${metrics?.githubScore || 0}%
Improve repository README quality, publish clear MIT licenses, and wire up GitHub actions CI.

### 3. LinkedIn Branding Status
Score: ${metrics?.linkedinScore || 0}%
Optimize summary copy with high keyword density to match recruiter search filters.

### 4. Technical & Behavioral Interview Readiness
Score: ${metrics?.interviewScore || 0}%
Perform structured mock practice loops under timer pressure to build speaking confidence.
`;
    }

    if (format === "markdown") {
      return new Response(markdown, {
        headers: {
          "Content-Type": "text/markdown",
          "Content-Disposition": `attachment; filename="${type}-report.md"`,
        },
      });
    }

    // HTML format
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${reportTitle}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #0b0f19; color: #f1f5f9; padding: 40px; line-height: 1.6; }
    h1 { color: #38bdf8; border-bottom: 2px solid #1e293b; padding-bottom: 12px; }
    h2, h3 { color: #6366f1; margin-top: 30px; }
    ul { padding-left: 20px; }
    li { margin-bottom: 8px; }
    .meta-box { background: rgba(255, 255, 255, 0.03); border: 1px solid #1e293b; border-radius: 12px; padding: 20px; margin-bottom: 30px; }
    .metric-value { font-weight: bold; color: #34d399; }
    hr { border: 0; border-top: 1px solid #1e293b; margin: 40px 0; }
  </style>
</head>
<body>
  <div style="max-width: 800px; margin: 0 auto;">
    <h1>${reportTitle}</h1>
    <p style="color: #64748b; font-size: 0.9em;">Generated by Career Agents on ${timestamp}</p>
    
    <div class="meta-box">
      <h3>Candidate Profile</h3>
      <p><strong>Name:</strong> ${profile?.name || "Guest User"}</p>
      <p><strong>Target Role:</strong> ${profile?.targetRole || "Software Engineer"}</p>
      <p><strong>Email:</strong> ${profile?.email || "N/A"}</p>
    </div>

    <h2>Core Performance Metrics</h2>
    <ul>
      <li>Overall Career Score: <span class="metric-value">${metrics?.careerScore || 0}/100</span></li>
      <li>Resume Score: <span class="metric-value">${metrics?.resumeScore || 0}/100</span></li>
      <li>GitHub Portfolio Score: <span class="metric-value">${metrics?.githubScore || 0}/100</span></li>
      <li>LinkedIn Visibility Score: <span class="metric-value">${metrics?.linkedinScore || 0}/100</span></li>
      <li>Mock Interview Score: <span class="metric-value">${metrics?.interviewScore || 0}/100</span></li>
    </ul>

    <hr />

    <div>
      ${markdown
        .split("\n\n")
        .map((paragraph) => {
          if (paragraph.startsWith("# ")) return `<h1>${paragraph.slice(2)}</h1>`;
          if (paragraph.startsWith("## ")) return `<h2>${paragraph.slice(3)}</h2>`;
          if (paragraph.startsWith("### ")) return `<h3>${paragraph.slice(4)}</h3>`;
          if (paragraph.startsWith("- ")) {
            const listItems = paragraph
              .split("\n")
              .map((item) => `<li>${item.slice(2).replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")}</li>`)
              .join("");
            return `<ul>${listItems}</ul>`;
          }
          return `<p>${paragraph.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")}</p>`;
        })
        .join("\n")}
    </div>
  </div>
</body>
</html>`;

    return new Response(html, {
      headers: {
        "Content-Type": "text/html",
        "Content-Disposition": `attachment; filename="${type}-report.html"`,
      },
    });
  } catch (e: any) {
    return NextResponse.json({ error: e.message || "Failed to generate report" }, { status: 500 });
  }
}
